### ISSUE TITLE
format_str() got an unexpected keyword argument 'line_length'

### ISSUE THREAD

**Issue by mattalhonte** [ryantam626/jupyterlab_code_formatter#15]
Just installed with the Black formatter.  Using anaconda with Python 3.7 as a base environment.  When I hit the "Apply Black Formatter" button, nothing happens, and I see this in the terminal window:

```
[E 21:34:52.006 LabApp] Uncaught exception POST /jupyterlab_code_formatter/format?1552613692000 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/jupyterlab_code_formatter/format?1552613692000', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/matt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/matt/anaconda3/lib/python3.7/site-packages/jupyterlab_code_formatter/handlers.py", line 66, in post
        data["code"], **(data["options"] or {})
      File "/home/matt/anaconda3/lib/python3.7/site-packages/jupyterlab_code_formatter/formatters.py", line 36, in format_code
        return format_str(code, **options)[:-1]
    TypeError: format_str() got an unexpected keyword argument 'line_length'
[W 21:34:52.007 LabApp] Unhandled error
[E 21:34:52.008 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "95",
      "Authorization": "token 46089f9488d32aa5e5443396608c78d57921a545d95d4540",
      "Origin": "http://localhost:8888",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36",
      "Dnt": "1",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "username-localhost-9990=\"2|1:0|10:1551064122|23:username-localhost-9990|44:MjQ2YzBlMjczYTdjNDUzMWE0NzIwM2ZkMTdiMGEyMTM=|d2e4285f794b2259e27c87a7758bab7be1f40ce0c613d8bc8a645b2aa06a48ea\"; _xsrf=2|8cc9511d|04ae6d8f70ec186122e19d1d6c5a524d|1552336278; username-localhost-8888=\"2|1:0|10:1552613687|23:username-localhost-8888|44:Nzk5YzUyNTU0MjBlNDBjNzk5MmVlY2Y1MWEwYzYyY2M=|518486b2e7d4ba6f961a09e6abe1458810e6142666057474823c7d9a1ef0c833\
""
    }
[E 21:34:52.009 LabApp] 500 POST /jupyterlab_code_formatter/format?1552613692000 (127.0.0.1) 3.34ms referer=http://localhost:8888/lab```

**Comment by ryantam626** [comment]
Hello, it seems the black library has changed their interface for `format_str`, for now you can downgrade black to `black==18.9b0` to get it working - will fix it on my side soon

**Comment by ryantam626** [comment]
Should be fixed now, let me know if it  doesn't work :smile:

**Comment by mattalhonte** [comment]
Woohoo, works great now!  Thanks!

**Comment by vadella** [comment]
I still get this problem with black version 19.3b0 and @ryantam626/jupyterlab_code_formatter v0.2.1

**Comment by ryantam626** [comment]
Hmm can you confirm that you have installed the latest server extension? The fix is not on the jupyterlab extension but on the server extension

**Comment by vadella** [comment]
:man_facepalming: 

jupyterlab_code_formatter is the only package I installed with pip instead of conda. So when it doesn't get updated when I do `conda update`. It is fixed now.

**Comment by ryantam626** [comment]
Good to hear :smile: It exist now in [conda-forge](https://anaconda.org/conda-forge/jupyterlab_code_formatter) btw
