### ISSUE TITLE
autopep8 adds new line at the end of the cell

### ISSUE THREAD

**Issue by asenchristov** [ryantam626/jupyterlab_code_formatter#54]
When using autopep8 it adds a new line at the the end of the cell. I tried the ignore option for couple of the autopep8 features, but couldn't prevent it from doing this.

**Comment by ryantam626** [comment]
Oops. That was an oversight, will get that fixed soon.

**Comment by ryantam626** [comment]
Should be fixed with v0.5.2 now!

**Comment by asenchristov** [comment]
i installed v0.5.2 
jupyter labextension list sais: 
@ryantam626/jupyterlab_code_formatter v0.5.2  enabled  OK
and there are no changes to the config.
Yet I still get a new line added to the end of the cell

**Comment by ryantam626** [comment]
Can you confirmed that you also upgraded the server extension? If not please run `pip install -U jupyterlab_code_formatter` in the correct env.

**Comment by asenchristov** [comment]
yes, this works, thanks.

**Comment by ryantam626** [comment]
Good to know :grin:
